language: python

env:
    global:
        - DEPENDS="numpy nibabel"
        - INSTALL_TYPE="pip"
        - EXTRA_WHEELS="https://5cf40426d9f06eb7461d-6fe47d9331aba7cd62fc36c7196769e4.ssl.cf2.rackcdn.com"
        - EXTRA_PIP_FLAGS="--find-links=$EXTRA_WHEELS"

python:
    - 3.4
    - 3.5
    - 3.6

matrix:
  include:
    - python: 2.7
      env:
        - DOCTESTS=1
        - DOC_DOCTEST=1
    # Absolute minimum dependencies
    - python: 2.7
      env:
        - DEPENDS="numpy==1.12.1 nibabel==2.1.0"
    - python: 2.7
      env:
        - INSTALL_TYPE=pipe
    - python: 2.7
      env:
        - INSTALL_TYPE=setup
#    - python: 2.7
#      env:
#        - INSTALL_TYPE=sdist
    - python: 2.7
      env:
        - DEPENDS=
        - INSTALL_TYPE=wheel
    - python: 2.7
      env:
        - DEPENDS=
        - INSTALL_TYPE=requirements

before_install:
    - python -m pip install --upgrade pip
    - pip install --upgrade virtualenv
    - virtualenv --python=python venv
    - python --version # just to check
    - source venv/bin/activate
    - pip install nose
    - if [ -n "$DEPENDS" ]; then
        pip install $EXTRA_PIP_FLAGS $DEPENDS;
      fi;
    - pip install coverage;
    - pip install coveralls;
    - if [ "${DOC_DOCTEST}" == "1" ]; then
        pip install sphinx;
      fi

install:
    - |
      if [ "$INSTALL_TYPE" == "pip" ]; then
          pip install .
      elif [ "$INSTALL_TYPE" == "pipe" ]; then
          pip install -e .
      elif [ "$INSTALL_TYPE" == "setup" ]; then
          python setup.py install
      elif [ "$INSTALL_TYPE" == "sdist" ]; then
          python setup.py egg_info  # check egg_info while we're here
          python setup.py sdist
          pip install $EXTRA_PIP_FLAGS dist/*.tar.gz
      elif [ "$INSTALL_TYPE" == "wheel" ]; then
          pip install wheel
          python setup.py bdist_wheel
          pip install $EXTRA_PIP_FLAGS dist/*.whl
      elif [ "$INSTALL_TYPE" == "requirements" ]; then
          pip install $EXTRA_PIP_FLAGS -r requirements.txt
          pip install .
      fi

script:

    - nosetests --with-coverage
    - mkdir for_testing
    - cd for_testing
    - if [ "${DOCTESTS}" == "1" ]; then
      DOCTEST_ARGS="--with-doctest";
      fi
    - nosetests $COVER_ARGS $DOCTEST_ARGS ../test
    - if [ "${DOC_DOCTEST}" == "1" ]; then
      cd ../docs ;
      sphinx-build -b html . _build/html ;
      fi

after_success:
    - coveralls
notifications:
  email: false